# Git
alias ga='git add'
alias gapa='git add -p'
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout'
alias gc!='git commit --amend'
alias gl='git pull'
alias glog='git log --oneline --decorate --graph'
alias gp='git push'
alias gst='git status'
